In [2]:
import numpy as np

In [3]:
a = [1, 2, 3, 4, 5]

In [4]:
type(a)

list

In [5]:
a1 = np.array(a)

In [6]:
a1

array([1, 2, 3, 4, 5])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a1.ndim

1

In [10]:
a1.shape

(5,)

In [12]:
a = np.array([[1,2,3],
             [4,5,6]])

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
type(a)

numpy.ndarray

In [15]:
a.ndim

2

In [17]:
a.shape

(2, 3)

In [18]:
a.dtype

dtype('int32')

In [19]:
a = np.ones(5)

In [20]:
a

array([1., 1., 1., 1., 1.])

In [22]:
a.dtype

dtype('float64')

In [23]:
a1 = np.ones(5, dtype = int)
a1

array([1, 1, 1, 1, 1])

In [24]:
a = np.ones((3,4))

In [25]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
a = np.ones((3,4,3))

In [27]:
a

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
a.ndim

3

In [30]:
a = np.zeros((2, 3, 4))

In [31]:
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [33]:
a = np.zeros((1,2) ,dtype=bool)

In [34]:
a

array([[False, False]])

In [49]:
a = np.arange(1,10)

In [50]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a = np.arange(12, 200, 5)

In [39]:
a

array([ 12,  17,  22,  27,  32,  37,  42,  47,  52,  57,  62,  67,  72,
        77,  82,  87,  92,  97, 102, 107, 112, 117, 122, 127, 132, 137,
       142, 147, 152, 157, 162, 167, 172, 177, 182, 187, 192, 197])

In [40]:
a = np.linspace(1, 10, 15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [44]:
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [51]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
a = np.arange(1,16)

In [53]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
len(a)

15

In [55]:
a.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [57]:
a = np.arange(1, 25).reshape(4,6)

In [58]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [62]:
b = np.arange(1, 25).reshape(2,4,3)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [63]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [64]:
a.ndim

2

In [65]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [66]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [67]:
a.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [87]:
a = np.arange(1, 10).reshape(3,3)
b = np.arange(1, 10).reshape(3,3)

In [69]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
a1 = np.add(a, b)

In [72]:
a1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [74]:
a1 = np.subtract(a, b)
a1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [75]:
a1 = np.divide(a, b)
a1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
a.min()

1

In [77]:
a.max()

9

In [88]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
a.min(axis=1)

array([1, 4, 7])

In [80]:
a.max(axis=0)

array([7, 8, 9])

In [81]:
a = np.sum(a)

In [82]:
a

45

In [83]:
np.argmax(a)

0

In [84]:
np.argmin(a)

0

In [89]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
np.argmax(a)

8

In [91]:
np.argmin(a)

0

In [92]:
np.sum(a, axis = 0)

array([12, 15, 18])

In [93]:
np.sum(a, axis = 1)

array([ 6, 15, 24])

In [94]:
np.trace(a)

15

In [95]:
np.mean(a)

5.0

In [96]:
np.std(a)

2.581988897471611

In [97]:
np.var(a)

6.666666666666667

In [98]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [99]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [100]:
a = np.arange(1, 101).reshape(10, 10)

In [101]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [102]:
a[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [103]:
a[3:6]

array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [104]:
a[3:6,3]

array([34, 44, 54])

In [105]:
a[3:6, 3:8]

array([[34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48],
       [54, 55, 56, 57, 58]])

In [107]:
a[:, 3:8:2]

array([[ 4,  6,  8],
       [14, 16, 18],
       [24, 26, 28],
       [34, 36, 38],
       [44, 46, 48],
       [54, 56, 58],
       [64, 66, 68],
       [74, 76, 78],
       [84, 86, 88],
       [94, 96, 98]])

In [109]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(1,10).reshape(3,3)

In [110]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [113]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [115]:
np.concatenate((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
np.concatenate((a,b), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [117]:
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [118]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
np.split(a, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [122]:
np.split(a, [2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [123]:
np.split(a, [2,3])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([], shape=(0, 3), dtype=int32)]

In [124]:
np.random.random()

0.8530039412381292

In [125]:
np.random.random(5)

array([0.47551546, 0.54370518, 0.3126779 , 0.5426139 , 0.80785434])

In [126]:
s = np.random.random((3,3))

In [127]:
s

array([[0.10685656, 0.23625424, 0.1782813 ],
       [0.22731752, 0.39681975, 0.80855979],
       [0.41897855, 0.65847176, 0.57099756]])

In [128]:
a = np.linspace(1, 15, 25)

In [129]:
a

array([ 1.        ,  1.58333333,  2.16666667,  2.75      ,  3.33333333,
        3.91666667,  4.5       ,  5.08333333,  5.66666667,  6.25      ,
        6.83333333,  7.41666667,  8.        ,  8.58333333,  9.16666667,
        9.75      , 10.33333333, 10.91666667, 11.5       , 12.08333333,
       12.66666667, 13.25      , 13.83333333, 14.41666667, 15.        ])

In [130]:
np.random.choice(a)

15.0

In [131]:
np.random.permutation(a)

array([ 9.75      ,  5.66666667,  8.        , 13.25      , 13.83333333,
        6.25      ,  2.16666667,  1.58333333, 12.66666667,  3.91666667,
        6.83333333,  9.16666667,  2.75      , 12.08333333, 10.91666667,
       10.33333333, 11.5       ,  8.58333333, 15.        ,  7.41666667,
        5.08333333,  3.33333333,  1.        ,  4.5       , 14.41666667])

In [132]:
np.random.uniform(1, 100, 25)

array([48.13962567, 30.04509403, 16.40837799, 23.71596963, 24.73269127,
       25.86501751, 70.03500931, 28.18649406,  9.98214439, 42.70998242,
       32.94691618, 20.13416816, 35.60523549, 74.45310896, 13.84742955,
       17.59504955, 29.19246596, 58.47908221, 79.04808084, 55.79801249,
       21.04083281, 44.0543337 , 76.28874811, 94.35811845, 93.19782329])

In [133]:
np.random.normal(20, 5, 50)

array([20.300024  , 16.67686196, 19.1058569 , 23.91957307, 15.25610689,
       28.17008296, 22.89500542, 22.80609017, 10.25438571, 17.5777958 ,
       19.96740748,  8.54957595,  8.94463411, 22.29986414, 21.77537181,
       15.81407316, 25.76013221, 17.16583945, 24.69143951, 27.60827412,
       15.20840168, 17.16030416, 21.33083351, 18.02945582, 20.43182355,
       22.3171128 , 13.53465577, 17.77774257, 18.73611659, 21.47293207,
       20.03684462, 23.17923968, 28.59961583, 14.73346901, 19.69679714,
       22.16630841, 24.18382811, 19.04778106, 20.86536722, 12.67873934,
       16.07866809, 20.61925625, 14.65404334, 15.81529297, 14.55249889,
       28.83847043, 19.28358618, 20.94454448, 20.92254536, 24.13070238])

In [134]:
s = "python"
s1 = "data science"

In [135]:
s+s1

'pythondata science'

In [136]:
np.char.split(s1)

array(list(['data', 'science']), dtype=object)

In [137]:
np.char.center(s, 15, '*')

array('*****python****', dtype='<U15')